export const ACCOUNTS = {
  PARTNER_BALANCE: "PARTNER_BALANCE",
  AGENT_BALANCE: "AGENT_BALANCE",
  COMPANY_CASH: "COMPANY_CASH",
  CASH_HELD_BY_CORRESPONDENT: "CASH_HELD_BY_CORRESPONDENT",
  CASH_HELD_BY_AGENT: "CASH_HELD_BY_AGENT",
  CASH_FUNDING_SOURCE: "CASH_FUNDING_SOURCE",
  CLEARING: "CLEARING",
  FX_POSITION: "FX_POSITION",
};
