export const ACCOUNTS = {
  PARTNER_BALANCE: "PARTNER_BALANCE",
  COMPANY_CASH: "COMPANY_CASH",
  CASH_FUNDING_SOURCE: "CASH_FUNDING_SOURCE",
  CLEARING: "CLEARING",
  FX_POSITION: "FX_POSITION",
};
